config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'home/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :addresses
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/address.rb
# == Schema Information
#
# Table name: addresses
#
#  id               :bigint           not null, primary key
#  address_building :string(255)      not null
#  address_city     :string(255)      not null
#  address_street   :string(255)      not null
#  post_code        :integer          not null
#  prefecture_code  :integer          not null
#  user_id          :bigint           not null
#
class Address < ApplicationRecord
  belongs_to :user

  validates :address_city, presence: true
  validates :address_street, presence: true
  validates :prefecture_code, presence: true
  validates :post_code, presence: true, length: { is: 7 } 

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name)&.code
  end
end

app/models/admin_user.rb
# == Schema Information
#
# Table name: admin_users
#
#  id                     :bigint           not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_admin_users_on_email                 (email) UNIQUE
#  index_admin_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  confirmation_sent_at   :datetime
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string(255)
#  unconfirmed_email      :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  has_many :addresses
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :fetch_address, only: [:edit, :update, :destroy]

  def index
    @addresses = current_user.addresses
  end

  def new
    @address = current_user.addresses.new
  end

  def create
    @address = current_user.addresses.build(address_params)
    if @address.save
      redirect_to addresses_path, notice: '登録しました'
    else
      render :new
    end
  end

  def edit
    render :new
  end

  def update
    if @address.update_attributes(address_params)
      redirect_to addresses_path, notice: '更新しました'
    else
      render :new
    end
  end

  def destroy
    @address.destroy
    redirect_to addresses_path, notice: "削除しました"
  end

  private

  def fetch_address
    @address = current_user.addresses.find(params[:id])
  end

  def address_params
    params.require(:address).permit(
      :address_building,
      :address_city,
      :address_street,
      :post_code,
      :prefecture_name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(title)
    render partial: 'shared/title', locals: {title: title}
  end

  def fetch_errors(resource,attribute)
    render partial: 'shared/form_error', locals: {resource: resource, attribute: attribute}
  end

  def error_class(resource, attribute)
    if resource.errors.messages[attribute].present?
      " is-invalid"
    else
      ""
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/addresses/index.html.haml
= title '住所一覧'
.card-columns
  -@addresses.each do |address|
    .card
      .card-body  
        = link_to address_path(address),method: :delete, class: 'close' do
          %span &times;
          
        %h5.card-title= Address.human_attribute_name(:post_code)   
        %p.card-text=address.post_code

        %h5.card-title= Address.human_attribute_name(:prefecture_name)
        %p.card-text=address.prefecture_name

        %h5.card-title= Address.human_attribute_name(:address_city)
        %p.card-text=address.address_city

        %h5.card-title= Address.human_attribute_name(:address_street)
        %p.card-text=address.address_street

        - if address.address_building.present?
          %h5.card-title= Address.human_attribute_name(:address_building)
          %p.card-text=address.address_building

        = link_to '編集', edit_address_path(address), class: 'btn btn-outline-primary'

app/views/addresses/new.html.haml
= title '住所登録'
.card
  .card-body
    =form_for @address,html: { class: 'needs-validation', novalidate: true} do |f|
      .form-group
        = f.label :post_code
        = f.text_field :post_code, class: 'form-control', minlength: 7, maxlength: 7, required: true, pattern: '^[0-9]{7}$'
        .invalid-feedback 正しい郵便番号を入力してください
        %small.form-text.text-muted　0000000（半角・ハイフンなし）
      .form-group
        = f.label :prefecture_name
        = f.collection_select :prefecture_name, JpPrefecture::Prefecture.all, :name, :name,{prompt: ""}, {class: 'form-control',include_blank: true, required: true}
        .invalid-feedback 都道府県を入力してください
      .form-group
        = f.label :address_city
        = f.text_field :address_city, class: 'form-control', required: true
        .invalid-feedback 市区町村を入力してください
      .form-group
        = f.label :address_street
        = f.text_field :address_street, class: 'form-control', required: true
        .invalid-feedback 番地を入力してください
      .form-group
        = f.label :address_building
        = f.text_field :address_building, class: 'form-control'
      = f.submit "保存", class: 'btn btn-primary'

=content_for :footer do
  = javascript_include_tag 'form_validation.js'
  :javascript
    $("#address_post_code").jpostal({
    postcode : [ "#address_post_code" ],
    address  : {
                  "#address_prefecture_name" : "%3",
                  "#address_address_city"            : "%4",
                  "#address_address_street"          : "%5%6%7"
                }
    })

app/views/home/index.html.haml
%h1 Home#index
%p Find me in app/views/home/index.html.erb

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SoilShare
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'shared/nav'
    = render 'shared/alert'
    .container
      = yield
      = yield :footer

app/views/shared/_alert.html.haml
- if notice
  #noticeModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :role => "dialog", :tabindex => "-1"}
    .modal-dialog{:role => "document"}
      .modal-content
        .alert.alert-success.mb-0
          = notice
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} ×
  - content_for :footer do
    :javascript
      $('#noticeModal').modal('show');
      
- if alert
  .alert.alert-danger= alert

app/views/shared/_form_error.html.haml
- if errors = resource.errors.full_messages_for(attribute)
  - errors.each do |error|
    .error-message=error

app/views/shared/_nav.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  = link_to 'SoilShare', root_path, class: 'navbar-brand'
  %button.navbar-toggler{"aria-controls" => "navbarNavAltMarkup", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarNavAltMarkup", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarNavAltMarkup.collapse.navbar-collapse
    .navbar-nav
      - if current_user
        = link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-item nav-link'
        = link_to '住所登録', new_address_path, class: 'nav-item nav-link'
        = link_to '住所一覧', addresses_path, class: 'nav-item nav-link'
      - else
        = link_to 'ログイン', new_user_session_path, class: 'nav-item nav-link'
        = link_to '新規登録', new_user_registration_path, class: 'nav-item nav-link'

app/views/shared/_title.html.haml
%h1.text-muted.my-5
  = title